### ISSUE TITLE
Not compatible with 1.20 (java.lang.NoSuchMethodError org.yaml.snakeyaml.parser.ParserImpl)

### ISSUE THREAD

**Issue by globau** [bundabrg/PortalNetwork#27]
Loading PortalNetwork-1.3.3 with Paper-1.20.1-43 results in:
```
[14:29:35] [Server thread/ERROR]: Error occurred while enabling PortalNetwork v1.3.3 (Is it up to date?)
java.lang.NoSuchMethodError: 'void org.yaml.snakeyaml.parser.ParserImpl.<init>(org.yaml.snakeyaml.reader.StreamReader)'
    at com.fasterxml.jackson.dataformat.yaml.YAMLParser.<init>(YAMLParser.java:178) ~[PortalNetwork-1.3.3.jar:?]
    at com.fasterxml.jackson.dataformat.yaml.YAMLFactory._createParser(YAMLFactory.java:466) ~[PortalNetwork-1.3.3.jar:?]
    at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:354) ~[PortalNetwork-1.3.3.jar:?]
    at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:15) ~[PortalNetwork-1.3.3.jar:?]
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3494) ~[PortalNetwork-1.3.3.jar:?]
    at au.com.grieve.portalnetwork.config.Config.load(Config.java:45) ~[PortalNetwork-1.3.3.jar:?]
    at au.com.grieve.portalnetwork.PortalNetwork.reload(PortalNetwork.java:159) ~[PortalNetwork-1.3.3.jar:?]
    at au.com.grieve.portalnetwork.PortalNetwork.initConfig(PortalNetwork.java:155) ~[PortalNetwork-1.3.3.jar:?]
    at au.com.grieve.portalnetwork.PortalNetwork.onEnable(PortalNetwork.java:69) ~[PortalNetwork-1.3.3.jar:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
    at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-43]
    at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-43]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-43]
    at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:547) ~[paper-1.20.1.jar:git-Paper-43]
    at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-43]
    at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.1.jar:git-Paper-43]
    at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-43]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-43]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-43]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by globau** [comment]
I'm still testing the changes in https://github.com/globau/PortalNetwork/commit/d3e283ebc102ffe91c5bf16311f64ebc3deec9eb but it appears to work on 1.20.1.

**Comment by bundabrg** [comment]
Are you telling me 1.20 doesn't include snakeyaml? That would increase the plugin size of every plugin ever made if they have to include it.

**Comment by bundabrg** [comment]
This seems to be someone with a similar issue with a commit to fix it if it helps. 

https://github.com/ElgarL/GroupManager/commit/81429dfc7c310e874424a683a24b869382095cb0

**Comment by globau** [comment]
Thanks I'll look at that approach

**Comment by globau** [comment]
1.20 includes snakeyaml, with a version bump that removed the constructor fasterxml.jackson used.
Bumping the version of fasterxml.jackson to 2.14.2 appears to have done the trick without the need to shade snakeyaml.
I still need to test https://github.com/globau/PortalNetwork/commit/89f7feddb492b149956292271c1fb160dfbddce6 properly, PR once that's happened.

**Comment by globau** [comment]
This was fixed by https://github.com/bundabrg/PortalNetwork/commit/ab1c8ec6fe1ed9a87b7975dbb3bb0f1ed3a5013f
